version: 2
jobs:
  build:
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
      - image: circleci/golang:1.13.1
    steps:
      - checkout
      - run: go vet ./...
      - run: go test ./...